version: "3.9"
services:
  authentication:
    build: ./Authentication
    container_name: authentication
    ports:
      - "8080:8080"
    depends_on:
      - auth-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_NAME: authentication_db
      DB_USER: postgres
      DB_PASS: postgres

  application:
    build: ./Application
    container_name: application
    ports:
      - "8081:8081"
    depends_on:
      - app-db
      - authentication
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: app-db
      DB_PORT: 5432
      DB_NAME: application_db
      DB_USER: postgres
      DB_PASS: postgres
      AUTH_SERVICE_URL: http://authentication:8080

  auth-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication_db
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
      - ./sql/auth:/docker-entrypoint-initdb.d

  app-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: application_db
    ports:
      - "5434:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
      - ./sql/app:/docker-entrypoint-initdb.d

volumes:
  auth-db-data:
  app-db-data:
